#!/bin/bash

redshift -m randr -l 56.8:60.6 -t 6500:4000 &
yeahconsole &
conky &

notification-thing &

aura -k
sleep 3
aura -d /mnt/volatiles/images ~/media/bgz

logtail_notify_lock="$XDG_RUNTIME_DIR"/logtail_notify.lock
touch "$logtail_notify_lock"
flock -n 0 <"$logtail_notify_lock" || pkill -g $(cat "$logtail_notify_lock")
setsid flock "$logtail_notify_lock"\
	-c 'logtail_notify\
		-i ~/media/appz/icons/biohazard_48x.png\
		-x "$XDG_RUNTIME_DIR"/logtail_notify.db\
		/var/log/syslog/stripped.log' &
echo $! >"$logtail_notify_lock"

sleep 10
xinitrc.input

exit 0
